version: '3.7'
services:
  tensorflow-3dmm-rendering-py3:
    build:
      context: .
      dockerfile: dockerfiles/tf2_0_py3/Dockerfile
      args:
        CUDA_BASE_VERSION: 10.1
        UBUNTU_VERSION: 18.04
        CUDNN_VERSION: 7.6.4.38
        TENSORFLOW_VERSION: 2.3.0
    image: xuan1918/tensorflow/3dmm-rendering:v0.3.2-py3
    environment:
        - NVIDIA_VISIBLE_DEVICES=all
    env_file:
      - tensorlfow_3dmm_rendering.env