version: '3.7'
services:
  tensorflow-3dmm-rendering-py3:
    build:
      context: .
      dockerfile: dockerfiles/tf2_0_py3/Dockerfile
      args:
        CUDA_BASE_VERSION: 10.0
        UBUNTU_VERSION: 18.04
        CUDNN_VERSION: 7.6.1.34
        TENSORFLOW_VERSION: 2.0.0-beta1
    image: xuan1918/tensorflow/3dmm-rendering:v0.1.0-py3
    environment:
        - NVIDIA_VISIBLE_DEVICES=all
    env_file:
      - tensorlfow_3dmm_rendering.env
  tensorflow-3dmm-rendering-py2:
    build:
      context: .
      dockerfile: dockerfiles/tf1_3_py2/Dockerfile
      args:
        CUDA_BASE_VERSION: 10.0
        UBUNTU_VERSION: 18.04
        CUDNN_VERSION: 7.6.1.34
        TENSORFLOW_VERSION: 2.0.0-beta1
    image: xuan1918/tensorflow/3dmm-rendering:v0.1.0-py2
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    env_file:
      - tensorlfow_3dmm_rendering.env