version: '3.7'
services:
  tensorflow-3dmm-rendering:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CUDA_BASE_VERSION: 10.0
        UBUNTU_VERSION: 18.04
        CUDNN_VERSION: 7.6.1.34
#        TENSORFLOW_VERSION: 2.0.0-beta1
        TENSORFLOW_VERSION: 1.13.1
    image: xuan1918/tensorflow/3dmm-rendering:v0.0.2
    environment:
        - NVIDIA_VISIBLE_DEVICES=all
    env_file:
      - tensorlfow_3dmm_rendering.env